var base = {
	init:function(){
		base.set();
	},
	set:function(){
		createForm.set({
			width:1000
			,title:"치공구/Tool 마스터 생성"
			,divisionType:null
			,service:"/master/tool/create"
			,beforeHandler:function(){
				return true;
			}
			,afterHandler:function(json){
				setTimeout(function(){
					hash.set({"service":"master/tool/list"});
				},500);
			},
			data:[{
				name:"기본정보"
				,data:
				[[
					{
						title:"Tool no"
						,id:"tool_no"
						,type:"input"
						,width:300
						,maxLength:50
						,dataType:"all"
						,must:true
					},
					{
						title:"S/N"
						,id:"tool_sn"
						,type:"input"
						,width:250
						,maxLength:50
						,dataType:"all"
						,must:true
					},
					{
						title:"Revision"
						,id:"revision"
						,type:"input"
						,width:100
						,maxLength:10
						,dataType:"all"
						,must:true
						,upper:true
						,notKor:true   
					},
					{
						title:"Tool Code"
						,id:"tool_code"
						,type:"select"
						,width:290
						,dataType:"all"
						,data:common.getCommonCode
						,dataParam:{"type":"tool_code"}
						,must:true
					}
				],[
					{
						title:"Project"
						,id:"project_code"
						,type:"select"
						,width:300
						,dataType:"all"
						,data:common.getProject
						,must:true
					},
					{
						title:"Class"
						,id:"tool_class"
						,type:"select"
						,width:180
						,dataType:"all"
						,data:common.getCommonCode
						,dataParam:{"type":"tool_class"}
					},
					{
						title:"검사주기"
						,id:"inspection_cycle"
						,type:"input"
						,width:140
						,dataType:"int"
					},
					{
						title:"주기기준"
						,id:"inspection_cycle_unit"
						,type:"select"
						,width:100
						,dataType:"all"
						,data:common.getCommonCode
						,dataParam:{"type":"inspection_cycle_unit"}
					},
					{
						title:"Location"
						,id:"location"
						,type:"input"
						,width:210
						,maxLength:400
						,dataType:"all"
					}
				],[				
					{
						title:"Spec"
						,id:"spec"
						,type:"input"
						,width:480
						,maxLength:500
						,dataType:"all"
						,must:true
					},
					{
						title:"Description"
						,id:"description"
						,type:"input"
						,width:480
						,maxLength:300
						,dataType:"all"
						,must:true
					}
				],[
					{
						title:"Remark"
						,id:"remark"
						,type:"input"
						,width:970
						,dataType:"all"
					}
				],[
					{
						title:"첨부파일"
						,id:"attach"
						,type:"attach"
						,width:970
						,height:180
						,multiple:true
						,immediate:false
						,row:4
						,path:"/master/tool/"
						,targetName:"/master/tool/attach"
						,accept:"*.*"
					}
				]]
			}
		]});
	}	
}
$(document).ready(base.init);