var base = {
	init:function(){
		base.set();
	},
	set:function(){
		createForm.set({
			width:1000
			,title:"자재 신규 생성"
			,divisionType:"tab"
			,service:"/master/material/create"
			,beforeHandler:function(form){
				return true;
			}
			,afterHandler:function(json){
				setTimeout(function(){
					hash.set({"service":"master/material/list"});
				},500);
			},
			data:[{
				name:"자재 기본정보"
				,data:
				[[
					{
						title:"Material"
						,id:"material"
						,type:"input"
						,width:430
						,dataType:"all"
						,must:true
					},{
						title:"Plant"
						,id:"plant"
						,type:"select"
						,width:200
						,data:common.getPlant
						,dataType:"all"
						,must:true
					},{
						title:"자재구분"
						,id:"material_type"
						,type:"select"
						,width:210
						,data:common.getCommonCode
						,dataParam:{"type":"material_type"}
						,dataType:"all"
					},{
						title:"기본 단위(UOM)"
						,id:"uom"
						,type:"select"
						,width:100
						,data:common.getUomCode
						,dataType:"all"
					}
				],[
					{
						title:"Description"
						,id:"description"
						,type:"input"
						,width:480
						,dataType:"all"
					},{
						title:"Spec"
						,id:"spec"
						,type:"input"
						,width:480
						,dataType:"all"
					}
				],[
					{
						title:"사이즈(Width)"
						,id:"width"
						,type:"input"
						,width:160
						,dataType:"decimal"
						,point:3
					},{
						title:"사이즈(Height)"
						,id:"height"
						,type:"input"
						,width:160
						,dataType:"decimal"
						,point:3
					},{
						title:"사이즈(Thickness)"
						,id:"thickness"
						,type:"input"
						,width:160
						,dataType:"decimal"
						,point:3
					},{
						title:"사이즈 단위(UOM)"
						,id:"size_uom"
						,type:"select"
						,width:140
						,data:common.getUomCode
						,dataParam:{"category":"L"}
						,dataType:"all"
					},{
						title:"무게(Weight)"
						,id:"weight"
						,type:"input"
						,width:160
						,dataType:"decimal"
						,point:3
					},{
						title:"무게 단위(UOM)"
						,id:"weight_uom"
						,type:"select"
						,width:140
						,data:common.getUomCode
						,dataParam:{"category":"W"}
						,dataType:"all"
					}
				],[
					{
						title:"Remark"
						,id:"remark"
						,type:"textarea"
						,width:970
						,height:100
					}
				],[
					{
						title:"첨부파일"
						,id:"attach"
						,type:"attach"
						,width:480
						,height:240
						,multiple:true
						,immediate:false
						,row:6
						,path:"/master/material/"
						,targetName:"/master/material/attach"
						,accept:"*.*"
					},{
						title:"형상정보"
						,id:"attach_photo"
						,type:"attach"
						,width:480
						,height:240
						,preview:true
						,multiple:true
						,immediate:false
						,row:6
						,path:"/master/material/"
						,targetName:"/master/material/photo"
						,maxSize:100
						,accept:".jpg,.png,.gif"
					}
				]]
			},{
				name:"PLANT 정보"
				,data:
				[[
					{
						title:"Project"
						,id:"project_code"
						,type:"select"
						,data:common.getProject
						,width:230
						,dataType:"all"
					},{
						title:"호기관리"
						,id:"tv_eff_flag"
						,type:"input"
						,titleAlign:"center"
						,switch:true
						,value:"X"
						,margin:"0 20px"
					}
				],[
					{
						title:"Remark"
						,id:"plant_remark"
						,type:"textarea"
						,width:970
						,height:100
					}
				]]
			}
		]});
	}	
}
$(document).ready(base.init);