var base = {
	init:function(){
		base.set();
	},
	set:function(){
		createForm.set({
			width:1000
			,title:"문서 생성"
			,divisionType:null
			,service:"/master/document/create"
			,beforeHandler:function(){

				alert($("#revision").val());
				return false;
			}
			,afterHandler:function(json){
				setTimeout(function(){
					hash.set({"service":"master/document/list"});
				},500);
			},
			data:[{
				name:"기본정보"
				,data:
				[[
					{
						title:"Document No"
						,id:"document_no"
						,type:"input"
						,width:310
						,dataType:"all"
						,maxLength:100
						,must:true
					},{
						title:"Type"
						,id:"document_type"
						,type:"select"
						,width:200
						,data:common.getCommonCode
						,dataParam:{"type":"document_type"}
						,dataType:"all"
						,must:true
					},{
						title:"Sheet"
						,id:"sheet"
						,type:"input"
						,width:210
						,maxLength:10
						,dataType:"all"
						,must:true
					},{
						title:"Revision"
						,id:"revision"
						,type:"input"
						,width:220
						,maxLength:10
						,dataType:"all"
						,must:true
						,upper:true
						,notKor:true
					}							
				],[
					{
						title:"Project"
						,id:"project_code"
						,type:"select"
						,width:580
						,data:common.getProject
						,dataType:"all"
						,must:true
					},					{
						title:"Customer Revision"
						,id:"customer_revision"
						,type:"input"
						,width:200
						,maxLength:50
						,dataType:"all"
					},{
						title:"만료일"
						,id:"expiration_date"
						,type:"date"
						,dataType:"date"
						,format:"yy/mm/dd"
					}    
				],[
					{
						title:"Name"
						,id:"document_name"
						,type:"input"
						,width:970
						,maxLength:300
						,dataType:"all"
					} 
				],[
					{
						title:"Remark"
						,id:"remark"
						,type:"input"
						,width:970
						,dataType:"all"
					}
				],[
					{
						title:"첨부파일"
						,id:"attach"
						,type:"attach"
						,width:970
						,height:180
						,multiple:true
						,immediate:false
						,row:4
						,path:"/master/document/"
						,targetName:"/master/document/attach"
						,accept:"*.*"
					}
				]]
			}
		]});
	}
}
$(document).ready(base.init);