var base = {
	init:function(){
		base.load();
	},
	load:function(){
		var param = {
			seq:hash.get("seq")
			,attach:true
			,attachTargetSeq:hash.get("seq")
			,attachTargetName:"/master/document/attach,/master/document/photo"
		};
		$.ajax({ 
			type:"POST",
			dataType:"json",
			url:"/master/document/read",
			data:param,
			success:function(json, status, res){
				try{
					base.set(json);
				}catch(e){
					console.log(e);
				}
			},
			error:function(e){
				console.log(e);
			}   

		});

	},
	set:function(data){
		var formData = data.data;
		var attachData = data.files;
		createForm.set({
			width:1000
			,title:"문서 조회"
			,makeType:"view"
			,divisionType:null
			,service:"/master/document/update"
			,defaultValue:{
				seq:hash.get("seq")
				,attachDelete:"delete" // "delete = forever delete,update = deletion_flag = 'X'"
			}
			,formData:formData
			,attachData:attachData
			,beforeHandler:function(){
				return true;
			}
			,afterHandler:function(json){
				setTimeout(function(){
					location.reload();
				},500);
			},
			data:[{
				name:"기본정보"
				,data:
				[[
					{
						title:"Document No"
						,id:"document_no"
						,type:"input"
						,width:330
						,dataType:"all"
						,must:true
					},{
						title:"Type"
						,id:"document_type"
						,type:"select"
						,width:210
						,data:common.getCommonCode
						,dataParam:{"type":"document_type"}
						,dataType:"all"
						,must:true
					},{
						title:"Sheet"
						,id:"sheet"
						,type:"input"
						,width:150
						,dataType:"all"
						,must:true
					},{
						title:"Revision"
						,id:"revision"
						,type:"input"
						,width:150
						,dataType:"all"
						,must:true
					},{
						title:"변경이력"
						,id:"history"
						,type:"customize"
						,html:"<button class='btn large changeHistory' onclick='base.revision()'>이력보기</button>"
						,width:80
					}							
				],[						
					{
						title:"Project"
						,id:"project_name"
						,type:"input"
						,width:610
						,dataType:"all"
						,must:true
					},{
						title:"Customer Revision"
						,id:"customer_revision"
						,type:"input"
						,width:170
						,dataType:"all"
					},{
						title:"만료일"
						,id:"expiration_date"
						,type:"input"
						,width:170
						,dataType:"all"
					}    
				],[
					{
						title:"Name"
						,id:"document_name"
						,type:"input"
						,width:970
						,dataType:"all"
					}
				],[
					{
						title:"Remark"
						,id:"remark"
						,type:"input"
						,width:970
						,dataType:"all"
					}
				],[
					{
						title:"첨부파일"
						,id:"attach"
						,type:"attach"
						,width:970
						,height:180
						,multiple:true
						,immediate:false
						,row:4
						,path:"/master/document/"
						,targetName:"/master/document/attach"
						,accept:"*.*"
					}
				]]
			}
		]});
	},
	revision:function(){
		popup.create({title:"변경 이력",width:950,height:750,type:"content",href:"/front/master/document/revision.html"});
	}
}
$(document).ready(base.init);